# -*- coding: utf-8 -*-
"""LibFHE version 1.0 2026May30Saturday.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10Z8yiqTRZjB9y6meZQf9Ncn3pQ-5aV6M
"""

!nvidia-smi

!pip install python-flint

!python cpu_main.py

import os
os.environ['CUDA_LAUNCH_BLOCKING'] = '1'


# main.py
from cpu_biginteger import BigInteger
from cpu_ring import Ring
from cpu_ciphertext import Ciphertext
# 導入你剛才命名的 Utils.py
from gpu_utils import FHEStorageManager, GPUDataConverter

import numpy as np
from numba import cuda

import os
import time
import random



import time
import copy
def generate_random_floats(count, lower_bound, upper_bound):
    random_floats = [complex(random.uniform(lower_bound, upper_bound), 0.0) for _ in range(count)]
    random_floats = [complex(random.uniform(lower_bound, upper_bound), random.uniform(lower_bound, upper_bound)) for _ in range(count)]
    return random_floats





# -*- coding: utf-8 -*-

from numba import uint32, uint64, int32  # 追加需要的 numba 型別
from numba import cuda, uint32, uint64
from numba import config, cuda
import numpy as np
import math, uuid as uuid_lib


config.CUDA_ENABLE_PYNVJITLINK = 1
config.CUDA_LOW_OCCUPANCY_WARNINGS = 0



import numpy as np
from numba import cuda
from gpu_scheme import Scheme
import gpu_constants as C
import gpu_constants as constants
from gpu_ciphertensor import CipherTensor


import numpy as np
from numba import cuda
import time


def main():

    # -------------------------------------------------------------------------------------------------- #


    logN=16
    logQ=1024
    logs = 2
    logp = 30
    logT = 2
    logq = 40

    sigma=3.2
    hwt=64
    context_params = {
        'N': 1 << logN,
        'D': 188
    }

    scheme = Scheme(context_params)
    scheme.generate_secret_key()
    scheme.generate_public_key()
    scheme.generate_conj_key()
    scheme.generate_mult_key()

    random_floats = generate_random_floats(2**logs, -5, 5) #(8, -5, 5)
    random_floats = generate_random_floats(2**logs, -5, 5) #(8, -5, 5)
    print('random_floats:', random_floats)
    #random_floats = [1.23456, 2.34567, 3.456789, 4.56789012]
    print('random_floats:', random_floats)




    #ce_officer.addBootKey(logs, logq + 4)
    scheme.addBootKey(logs, logq + 4)
    scheme.addBootRing(logs, logq + 4)

    cts = scheme.encrypt_pairwise_upon(
        logp,
        logQ,
        [random_floats[:] for _ in range(4)]
    )

    print('cts.logp---------')
    print(cts.logp)
    print('cts.logq---------')
    print(cts.logq)
    print('cts.logs---------')
    print(cts.logs)
    print('cts.shape---------')
    print(cts.shape)
    print('cts.data---------')
    print(cts.data)
    print('cts.device_ptr---------')
    print(cts.device_ptr)
    print('++++++++++++++++++')


    scheme.bootstrap_pairwise_into(cts, logq, logQ, logT)

    print('++++++++++++++++++')
    print('cts.logp---------')
    print(cts.logp)
    print('cts.logq---------')
    print(cts.logq)
    print('cts.logs---------')
    print(cts.logs)
    print('cts.shape---------')
    print(cts.shape)
    print('cts.data---------')
    print(cts.data)
    print('cts.device_ptr---------')
    print(cts.device_ptr)


    cuda.synchronize()
    start_time = time.perf_counter()

    scheme.bootstrap_pairwise_into(cts, logq, logQ, logT)
    cuda.synchronize()

    end_time = time.perf_counter()
    elapsed_time = end_time - start_time
    print(f"bootstrap_pairwise_into的平均行時間: {elapsed_time:.4f} 秒")


    start_time = time.perf_counter()
    result = scheme.decrypt_pairwise_upon(cts)
    result = result[0]
    end_time = time.perf_counter()
    elapsed_time = end_time - start_time
    print(f"一個密文張量解密的平均行時間: {elapsed_time:.4f} 秒")
    print()
    print('+++++++++++++++++++++++++++ bootstrap_pairwise_into +++++++++++++++++++++++++++')
    print()
    for i in range(4):
        error0 = math.fabs(random_floats[i].real - result[i].real )
        error1 = math.fabs(random_floats[i].imag - result[i].imag )
        print(error0+error1, ', ', random_floats[i].real, '  ==  ', result[i].real, ' : ', ', ', random_floats[i].imag, '  ==  ', result[i].imag)
    print()
    print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
    print()
    for i in range(4):
        print(random_floats[i], '  ---  ', result[i])

    print()
    print('+++++++++++++++++++++++++++ bootstrap_pairwise_into +++++++++++++++++++++++++++')
    print()




    logN=16
    logQ=1024
    logs = 0
    logp = 30
    logT = 2
    logq = 40

    sigma=3.2
    hwt=64
    context_params = {
        'N': 1 << logN,
        'D': 188
    }

    scheme = Scheme(context_params)
    scheme.generate_secret_key()
    scheme.generate_public_key()
    scheme.generate_conj_key()
    scheme.generate_mult_key()

    random_floats = generate_random_floats(2**logs, -5, 5) #(8, -5, 5)
    random_floats = generate_random_floats(2**logs, -5, 5) #(8, -5, 5)
    print('random_floats:', random_floats)
    random_floats = [1.23456, 2.34567, 3.456789, 4.56789012]
    random_floats = [1.23456789]
    print('random_floats:', random_floats)


    #ce_officer.addBootKey(logs, logq + 4)
    scheme.addBootKey(logs, logq + 4)
    scheme.addBootRing(logs, logq + 4)

    cts = scheme.encrypt_pairwise_upon(
        logp,
        logQ,
        [random_floats[:] for _ in range(4)]
    )

    print('cts.logp---------')
    print(cts.logp)
    print('cts.logq---------')
    print(cts.logq)
    print('cts.logs---------')
    print(cts.logs)
    print('cts.shape---------')
    print(cts.shape)
    print('cts.data---------')
    print(cts.data)
    print('cts.device_ptr---------')
    print(cts.device_ptr)
    print('++++++++++++++++++')


    scheme.bootstrap_pairwise_into(cts, logq, logQ, logT)

    print('++++++++++++++++++')
    print('cts.logp---------')
    print(cts.logp)
    print('cts.logq---------')
    print(cts.logq)
    print('cts.logs---------')
    print(cts.logs)
    print('cts.shape---------')
    print(cts.shape)
    print('cts.data---------')
    print(cts.data)
    print('cts.device_ptr---------')
    print(cts.device_ptr)


    cuda.synchronize()
    start_time = time.perf_counter()

    scheme.bootstrap_pairwise_into(cts, logq, logQ, logT)
    cuda.synchronize()

    end_time = time.perf_counter()
    elapsed_time = end_time - start_time
    print(f"bootstrap_pairwise_into的平均行時間: {elapsed_time:.4f} 秒")


    start_time = time.perf_counter()
    result = scheme.decrypt_pairwise_upon(cts)
    result = result[0]
    end_time = time.perf_counter()
    elapsed_time = end_time - start_time
    print(f"GPUDataConverter.from_numpy_array的平均行時間: {elapsed_time:.4f} 秒")
    print()
    print('+++++++++++++++++++++++++++ bootstrap_pairwise_into +++++++++++++++++++++++++++')
    print()
    for i in range(1):
        error0 = math.fabs(random_floats[i].real - result[i].real )
        error1 = math.fabs(random_floats[i].imag - result[i].imag )
        print(error0+error1, ', ', random_floats[i].real, '  ==  ', result[i].real, ' : ', ', ', random_floats[i].imag, '  ==  ', result[i].imag)
    print()
    print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
    print()
    for i in range(1):
        print(random_floats[i], '  ---  ', result[i])

    print()
    print('+++++++++++++++++++++++++++ bootstrap_pairwise_into +++++++++++++++++++++++++++')
    print()

    return 0


if __name__ == "__main__":
    main()

import os
os.environ['CUDA_LAUNCH_BLOCKING'] = '1'


# main.py
from cpu_biginteger import BigInteger
from cpu_ring import Ring
from cpu_ciphertext import Ciphertext
# 導入你剛才命名的 Utils.py
from gpu_utils import FHEStorageManager, GPUDataConverter

import numpy as np
from numba import cuda

import os
import time
import random



import time
import copy
def generate_random_floats(count, lower_bound, upper_bound):
    random_floats = [complex(random.uniform(lower_bound, upper_bound), 0.0) for _ in range(count)]
    random_floats = [complex(random.uniform(lower_bound, upper_bound), random.uniform(lower_bound, upper_bound)) for _ in range(count)]
    return random_floats





# -*- coding: utf-8 -*-

from numba import uint32, uint64, int32  # 追加需要的 numba 型別
from numba import cuda, uint32, uint64
from numba import config, cuda
import numpy as np
import math, uuid as uuid_lib


config.CUDA_ENABLE_PYNVJITLINK = 1
config.CUDA_LOW_OCCUPANCY_WARNINGS = 0



import numpy as np
from numba import cuda
from gpu_scheme import Scheme
import gpu_constants as C
import gpu_constants as constants
from gpu_ciphertensor import CipherTensor


import numpy as np
from numba import cuda
import time


def main():

    # -------------------------------------------------------------------------------------------------- #


    logN=16
    logQ=1024
    logs = 2
    logp = 30
    logT = 2
    logq = 40

    sigma=3.2
    hwt=64
    context_params = {
        'N': 1 << logN,
        'D': 188
    }

    scheme = Scheme(context_params)
    scheme.generate_secret_key()
    scheme.generate_public_key()
    scheme.generate_conj_key()
    scheme.generate_mult_key()

    random_floats = generate_random_floats(2**logs, -5, 5) #(8, -5, 5)
    random_floats = generate_random_floats(2**logs, -5, 5) #(8, -5, 5)
    print('random_floats:', random_floats)
    #random_floats = [1.23456, 2.34567, 3.456789, 4.56789012]
    print('random_floats:', random_floats)

    # -------------------------------------------------------------------------------------------------- #



    # ============================================================
    # 測試 1：copy() —— 傳統深拷貝
    # ============================================================

    print()
    print("#################### TEST 1 : copy() ####################")
    print()

    cts_a = scheme.encrypt_pairwise_upon(
        60,
        logQ,
        [random_floats[:] for _ in range(4)]
    )


    # 深拷貝
    cts_b = cts_a.copy()

    # 修改 a
    scheme.sub_pairwise_into(cts_a, cts_b)

    cuda.synchronize()

    # 驗證：
    # 如果 copy() 真的是深拷貝
    # 則：
    #   a = a - b = original - original = 0
    #   b 保持原值不變

    result_a = scheme.decrypt_pairwise_upon(cts_a)[0]
    result_b = scheme.decrypt_pairwise_upon(cts_b)[0]

    print("驗證 cts_a 是否變成 0")
    print()

    for i in range(4):
        print(result_a[i])

    print()
    print("驗證 cts_b 是否保持原值")
    print()

    for i in range(4):

        error0 = math.fabs(
            random_floats[i].real - result_b[i].real
        )

        error1 = math.fabs(
            random_floats[i].imag - result_b[i].imag
        )

        print(
            error0 + error1,
            ', ',
            random_floats[i],
            ' == ',
            result_b[i]
        )

    print()
    print("#########################################################")
    print()



    # ============================================================
    # 測試 2：copy_from() —— 就地吸納
    # ============================================================

    print()
    print("################# TEST 2 : copy_from() ##################")
    print()

    cts_a = scheme.encrypt_pairwise_upon(
        60,
        logQ,
        [random_floats[:] for _ in range(4)]
    )

    cts_b = scheme.encrypt_pairwise_upon(
        60,
        logQ,
        [random_floats[:] for _ in range(4)]
    )

    # b 吸納 a
    cts_b.copy_from(cts_a)

    cuda.synchronize()

    # 解密驗證
    result = scheme.decrypt_pairwise_upon(cts_b)[0]

    print("驗證 cts_b 是否完全等於 cts_a")
    print()

    for i in range(4):

        error0 = math.fabs(
            random_floats[i].real - result[i].real
        )

        error1 = math.fabs(
            random_floats[i].imag - result[i].imag
        )

        print(
            error0 + error1,
            ', ',
            random_floats[i],
            ' == ',
            result[i]
        )

    print()
    print("#########################################################")
    print()



    # ============================================================
    # 測試 3：copy_into() —— 就地注入
    # ============================================================

    print()
    print("################# TEST 3 : copy_into() ##################")
    print()

    cts_a = scheme.encrypt_pairwise_upon(
        60,
        logQ,
        [random_floats[:] for _ in range(4)]
    )

    cts_b = scheme.encrypt_pairwise_upon(
        60,
        logQ,
        [random_floats[:] for _ in range(4)]
    )

    # a 注入 b
    cts_a.copy_into(cts_b)

    cuda.synchronize()

    # 驗證
    result = scheme.decrypt_pairwise_upon(cts_b)[0]

    print("驗證 cts_b 是否被 cts_a 覆蓋")
    print()

    for i in range(4):

        error0 = math.fabs(
            random_floats[i].real - result[i].real
        )

        error1 = math.fabs(
            random_floats[i].imag - result[i].imag
        )

        print(
            error0 + error1,
            ', ',
            random_floats[i],
            ' == ',
            result[i]
        )

    print()
    print("#########################################################")
    print()



    # ============================================================
    # 測試 4：copy_from() 是否真正避免 allocation
    # ============================================================

    print()
    print("######## TEST 4 : inplace overwrite benchmark ###########")
    print()

    cts_a = scheme.encrypt_pairwise_upon(
        60,
        logQ,
        [random_floats[:] for _ in range(4)]
    )

    cts_b = scheme.encrypt_pairwise_upon(
        60,
        logQ,
        [random_floats[:] for _ in range(4)]
    )

    cuda.synchronize()

    start_time = time.perf_counter()

    for _ in range(100):
        cts_b.copy_from(cts_a)

    cuda.synchronize()

    end_time = time.perf_counter()

    elapsed_time = end_time - start_time

    print(f"100 次 copy_from 耗時: {elapsed_time:.6f} 秒")

    print()
    print("#########################################################")
    print()



    # ============================================================
    # 測試 5：copy() vs copy_from() 性能比較
    # ============================================================

    print()
    print("############ TEST 5 : copy benchmark ####################")
    print()

    cts_a = scheme.encrypt_pairwise_upon(
        60,
        logQ,
        [random_floats[:] for _ in range(4)]
    )

    # ------------------------------------------------------------
    # copy()
    # ------------------------------------------------------------

    cuda.synchronize()

    start_time = time.perf_counter()

    for _ in range(20):

        tmp = cts_a.copy()

    cuda.synchronize()

    end_time = time.perf_counter()

    elapsed_copy = end_time - start_time

    print(f"20 次 copy() 耗時: {elapsed_copy:.6f} 秒")

    # ------------------------------------------------------------
    # copy_from()
    # ------------------------------------------------------------

    cts_b = CipherTensor(
        60,
        logQ,
        logs,
        cts_a.shape
    )

    cuda.synchronize()

    start_time = time.perf_counter()

    for _ in range(20):

        cts_b.copy_from(cts_a)

    cuda.synchronize()

    end_time = time.perf_counter()

    elapsed_copy_from = end_time - start_time

    print(f"20 次 copy_from() 耗時: {elapsed_copy_from:.6f} 秒")

    print()

    if elapsed_copy_from > 0:
        print(
            "copy() / copy_from() 加速比 = ",
            elapsed_copy / elapsed_copy_from
        )

    print()
    print("#########################################################")
    print()






    # ----------------------------------------------------------------------------------------------------------- #











    cts_a = CipherTensor(60, logQ, logs, (2,4,188, 1<<16))
    cuda.synchronize()
    start_time = time.perf_counter()
    cts_a = scheme.encrypt_pairwise_upon(60, logQ, [random_floats[:]  for _ in range(4)])
    scheme.negate_pairwise_into(cts_a)
    cuda.synchronize()
    end_time = time.perf_counter()
    elapsed_time = end_time - start_time

    cts_a = CipherTensor(60, logQ, logs, (2,4,188, 1<<16))
    cts_a = scheme.encrypt_pairwise_upon(60, logQ, [random_floats[:]  for _ in range(4)])
    cuda.synchronize()
    start_time = time.perf_counter()
    scheme.negate_pairwise_into(cts_a)
    cuda.synchronize()
    end_time = time.perf_counter()
    elapsed_time = end_time - start_time
    print(f"一個密文張量negate的平均行時間: {elapsed_time:.4f} 秒")

    start_time = time.perf_counter()
    result = scheme.decrypt_pairwise_upon(cts_a)
    result = result[0]
    end_time = time.perf_counter()
    elapsed_time = end_time - start_time
    print(f"一個密文張量解密的平均行時間: {elapsed_time:.4f} 秒")
    print()
    print('+++++++++++++++++++++++++++ negate_pairwise_into +++++++++++++++++++++++++++')
    print()
    for i in range(4):
        error0 = math.fabs(random_floats[i].real + result[i].real )
        error1 = math.fabs(random_floats[i].imag + result[i].imag )
        print(error0+error1, ', ', -random_floats[i].real, '  ==  ', result[i].real, ' : ', ', ', -random_floats[i].imag, '  ==  ', result[i].imag)
    print()
    print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
    print()
    for i in range(4):
        print(-random_floats[i], '  ---  ', result[i])

    print()
    print('+++++++++++++++++++++++++++ negate_pairwise_into +++++++++++++++++++++++++++')
    print()





    cts_a = CipherTensor(60, logQ, logs, (2,4,188, 1<<16))
    cuda.synchronize()
    start_time = time.perf_counter()
    cts_a = scheme.encrypt_pairwise_upon(60, logQ, [random_floats[:]  for _ in range(4)])
    scheme.moddownBy_pairwise_into(cts_a, 15)
    cuda.synchronize()
    end_time = time.perf_counter()
    elapsed_time = end_time - start_time

    cts_a = CipherTensor(60, logQ, logs, (2,4,188, 1<<16))
    cts_a = scheme.encrypt_pairwise_upon(60, logQ, [random_floats[:]  for _ in range(4)])
    cuda.synchronize()
    start_time = time.perf_counter()
    scheme.moddownBy_pairwise_into(cts_a, 15)
    cuda.synchronize()
    end_time = time.perf_counter()
    elapsed_time = end_time - start_time
    print(f"一個密文張量moddown的平均行時間: {elapsed_time:.4f} 秒")

    start_time = time.perf_counter()
    result = scheme.decrypt_pairwise_upon(cts_a)
    result = result[0]
    end_time = time.perf_counter()
    elapsed_time = end_time - start_time
    print(f"一個密文張量解密的平均行時間: {elapsed_time:.4f} 秒")
    print()
    print('+++++++++++++++++++++++++++ moddownBy_pairwise_into +++++++++++++++++++++++++++')
    print()
    for i in range(4):
        error0 = math.fabs(random_floats[i].real - result[i].real )
        error1 = math.fabs(random_floats[i].imag - result[i].imag )
        print(error0+error1, ', ', random_floats[i].real, '  ==  ', result[i].real, ' : ', ', ', random_floats[i].imag, '  ==  ', result[i].imag)
    print()
    print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
    print()
    for i in range(4):
        print(random_floats[i], '  ---  ', result[i])

    print()
    print('+++++++++++++++++++++++++++ moddownBy_pairwise_into +++++++++++++++++++++++++++')
    print()








    cts_a = CipherTensor(60, logQ, logs, (2,4,188, 1<<16))
    cuda.synchronize()
    start_time = time.perf_counter()
    cts_a = scheme.encrypt_pairwise_upon(60, logQ, [random_floats[:]  for _ in range(4)])
    scheme.rescaleBy_pairwise_into(cts_a, 15)
    cuda.synchronize()
    end_time = time.perf_counter()
    elapsed_time = end_time - start_time

    cts_a = CipherTensor(60, logQ, logs, (2,4,188, 1<<16))
    cts_a = scheme.encrypt_pairwise_upon(60, logQ, [random_floats[:]  for _ in range(4)])
    cuda.synchronize()
    start_time = time.perf_counter()
    scheme.rescaleBy_pairwise_into(cts_a, 15)
    cuda.synchronize()
    end_time = time.perf_counter()
    elapsed_time = end_time - start_time
    print(f"一個密文張量rescale的平均行時間: {elapsed_time:.4f} 秒")

    start_time = time.perf_counter()
    result = scheme.decrypt_pairwise_upon(cts_a)
    result = result[0]
    end_time = time.perf_counter()
    elapsed_time = end_time - start_time
    print(f"一個密文張量解密的平均行時間: {elapsed_time:.4f} 秒")
    print()
    print('+++++++++++++++++++++++++++ rescaleBy_pairwise_into +++++++++++++++++++++++++++')
    print()
    for i in range(4):
        error0 = math.fabs(random_floats[i].real - result[i].real )
        error1 = math.fabs(random_floats[i].imag - result[i].imag )
        print(error0+error1, ', ', random_floats[i].real, '  ==  ', result[i].real, ' : ', ', ', random_floats[i].imag, '  ==  ', result[i].imag)
    print()
    print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
    print()
    for i in range(4):
        print(random_floats[i], '  ---  ', result[i])

    print()
    print('+++++++++++++++++++++++++++ rescaleBy_pairwise_into +++++++++++++++++++++++++++')
    print()








    cts_a = CipherTensor(60, logQ, logs, (2,4,188, 1<<16))
    cuda.synchronize()
    start_time = time.perf_counter()
    cts_a = scheme.encrypt_pairwise_upon(60, logQ, [random_floats[:]  for _ in range(4)])
    scheme.rescaleBy_pairwise_into(cts_a, 15)
    cuda.synchronize()
    end_time = time.perf_counter()
    elapsed_time = end_time - start_time

    cts_a = CipherTensor(60, logQ, logs, (2,4,188, 1<<16))
    cts_a = scheme.encrypt_pairwise_upon(60, logQ, [random_floats[:]  for _ in range(4)])
    cuda.synchronize()
    start_time = time.perf_counter()
    scheme.rescaleBy_pairwise_into(cts_a, 15)
    cuda.synchronize()
    end_time = time.perf_counter()
    elapsed_time = end_time - start_time
    print(f"一個密文張量rescale的平均行時間: {elapsed_time:.4f} 秒")

    start_time = time.perf_counter()
    result = scheme.decrypt_pairwise_upon(cts_a)
    result = result[0]
    end_time = time.perf_counter()
    elapsed_time = end_time - start_time
    print(f"一個密文張量解密的平均行時間: {elapsed_time:.4f} 秒")
    print()
    print('+++++++++++++++++++++++++++ rescaleBy_pairwise_into +++++++++++++++++++++++++++')
    print()
    for i in range(4):
        error0 = math.fabs(random_floats[i].real - result[i].real )
        error1 = math.fabs(random_floats[i].imag - result[i].imag )
        print(error0+error1, ', ', random_floats[i].real, '  ==  ', result[i].real, ' : ', ', ', random_floats[i].imag, '  ==  ', result[i].imag)
    print()
    print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
    print()
    for i in range(4):
        print(random_floats[i], '  ---  ', result[i])

    print()
    print('+++++++++++++++++++++++++++ rescaleBy_pairwise_into +++++++++++++++++++++++++++')
    print()




    cts_a = CipherTensor(60, logQ, logs, (2,4,188, 1<<16))
    cuda.synchronize()
    start_time = time.perf_counter()
    cts_a = scheme.encrypt_pairwise_upon(60, logQ, [random_floats[:]  for _ in range(4)])
    scheme.conjugate_pairwise_into(cts_a)
    cuda.synchronize()
    end_time = time.perf_counter()
    elapsed_time = end_time - start_time

    cts_a = CipherTensor(60, logQ, logs, (2,4,188, 1<<16))
    cts_a = scheme.encrypt_pairwise_upon(60, logQ, [random_floats[:]  for _ in range(4)])
    cuda.synchronize()
    start_time = time.perf_counter()
    scheme.conjugate_pairwise_into(cts_a)
    cuda.synchronize()
    end_time = time.perf_counter()
    elapsed_time = end_time - start_time
    print(f"一個個密文張量conjugate_pairwise_into生成的平均行時間: {elapsed_time:.4f} 秒")

    start_time = time.perf_counter()
    result = scheme.decrypt_pairwise_upon(cts_a)
    result = result[0]
    end_time = time.perf_counter()
    elapsed_time = end_time - start_time
    print(f"一個密文張量解密的平均行時間: {elapsed_time:.4f} 秒")
    print()
    print('+++++++++++++++++++++++++++ conjugate_pairwise_into +++++++++++++++++++++++++++')
    print()
    for i in range(4):
        error0 = math.fabs(random_floats[i].real - result[i].real )
        error1 = math.fabs(random_floats[i].imag + result[i].imag )
        print(error0+error1, ', ', random_floats[i].real, '  ==  ', result[i].real, ' : ', ', ', random_floats[i].imag, '  ==  ', -result[i].imag)
    print()
    print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
    print()
    for i in range(4):
        print(random_floats[i], '  ---  ', result[i])

    print()
    print('+++++++++++++++++++++++++++ conjugate_pairwise_into +++++++++++++++++++++++++++')
    print()




    cts_a = CipherTensor(60, logQ, logs, (2,4,188, 1<<16))
    cts_a = scheme.encrypt_pairwise_upon(60, logQ, [random_floats[:]  for _ in range(4)])
    cuda.synchronize()
    start_time = time.perf_counter()
    scheme.mult_pairwise_into(cts_a, cts_a)
    cuda.synchronize()
    end_time = time.perf_counter()
    elapsed_time = end_time - start_time

    start_time = time.perf_counter()
    result = scheme.decrypt_pairwise_upon(cts_a)
    result = result[0]
    end_time = time.perf_counter()
    elapsed_time = end_time - start_time
    print(f"一個密文張量解密的平均行時間: {elapsed_time:.4f} 秒")
    print()
    print('+++++++++++++++++++++++++++ mult_pairwise_into +++++++++++++++++++++++++++')
    print()
    for i in range(4):
        error0 = math.fabs(((random_floats[i])**2).real - result[i].real )
        error1 = math.fabs(((random_floats[i])**2).imag - result[i].imag )
        print(error0+error1, ', ', ((random_floats[i])**2).real, '  ==  ', result[i].real, ' : ', ', ', ((random_floats[i])**2).imag, '  ==  ', result[i].imag)
    print()
    print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
    print()
    for i in range(4):
        print(((random_floats[i])**2), '  ---  ', result[i])

    print()
    print('+++++++++++++++++++++++++++ mult_pairwise_into +++++++++++++++++++++++++++')
    print()







    scheme.generate_left_rot_key(2)
    scheme.leftrote_broadcast_into(cts_a, 2)


    cts_a = CipherTensor(60, logQ, logs, (2,4,188, 1<<16))
    cts_a = scheme.encrypt_pairwise_upon(60, logQ, [random_floats[:]  for _ in range(4)])
    cuda.synchronize()
    start_time = time.perf_counter()
    scheme.leftrote_broadcast_into(cts_a, 2)
    cuda.synchronize()
    end_time = time.perf_counter()
    elapsed_time = end_time - start_time

    start_time = time.perf_counter()
    result = scheme.decrypt_pairwise_upon(cts_a)
    result = result[0]
    end_time = time.perf_counter()
    elapsed_time = end_time - start_time
    print(f"一個密文張量解密的平均行時間: {elapsed_time:.4f} 秒")
    print()
    print('+++++++++++++++++++++++++++ leftrote_broadcast_into +++++++++++++++++++++++++++')
    print()
    for i in range(4):
        error0 = math.fabs(random_floats[(i+2)%(1<<logs)].real - result[i].real )
        error1 = math.fabs(random_floats[(i+2)%(1<<logs)].imag - result[i].imag )
        print(error0+error1, ', ', random_floats[(i+2)%(1<<logs)].real, '  ==  ', result[i].real, ' : ', ', ', random_floats[(i+2)%(1<<logs)].imag, '  ==  ', result[i].imag)
    print()
    print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
    print()
    for i in range(4):
        print(random_floats[(i+2)%(1<<logs)], '  ---  ', result[i])

    print()
    print('+++++++++++++++++++++++++++ leftrote_broadcast_into +++++++++++++++++++++++++++')
    print()





    cts_a = CipherTensor(60, logQ, logs, (2,4,188, 1<<16))
    cts_a = scheme.encrypt_pairwise_upon(60, logQ, [random_floats[:]  for _ in range(4)])
    cts_b = CipherTensor(60, logQ, logs, (2,4,188, 1<<16))
    cts_b = scheme.encrypt_pairwise_upon(60, logQ, [random_floats[:]  for _ in range(4)])
    scheme.add_pairwise_into(cts_a, cts_b)

    cts_a = CipherTensor(60, logQ, logs, (2,4,188, 1<<16))
    cts_a = scheme.encrypt_pairwise_upon(60, logQ, [random_floats[:]  for _ in range(4)])
    cts_b = CipherTensor(60, logQ, logs, (2,4,188, 1<<16))
    cts_b = scheme.encrypt_pairwise_upon(60, logQ, [random_floats[:]  for _ in range(4)])
    cuda.synchronize()
    start_time = time.perf_counter()
    scheme.add_pairwise_into(cts_a, cts_b)
    cuda.synchronize()
    end_time = time.perf_counter()
    elapsed_time = end_time - start_time
    print(f"兩個密文相加的平均行時間: {elapsed_time:.4f} 秒")

    start_time = time.perf_counter()
    result = scheme.decrypt_pairwise_upon(cts_a)
    result = result[0]
    end_time = time.perf_counter()
    elapsed_time = end_time - start_time
    print(f"一個密文張量解密的平均行時間: {elapsed_time:.4f} 秒")
    print()
    print('+++++++++++++++++++++++++++ add_pairwise_into +++++++++++++++++++++++++++')
    print()
    for i in range(4):
        error0 = math.fabs(random_floats[i].real*2 - result[i].real )
        error1 = math.fabs(random_floats[i].imag*2 - result[i].imag )
        print(error0+error1, ', ', random_floats[i].real*2, '  ==  ', result[i].real, ' : ', ', ', random_floats[i].imag*2, '  ==  ', result[i].imag)
    print()
    print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
    print()
    for i in range(4):
        print(random_floats[i]*2, '  ---  ', result[i])

    print()
    print('+++++++++++++++++++++++++++ add_pairwise_into +++++++++++++++++++++++++++')
    print()




    cts_a = CipherTensor(60, logQ, logs, (2,4,188, 1<<16))
    cts_a = scheme.encrypt_pairwise_upon(60, logQ, [random_floats[:]  for _ in range(4)])
    cts_b = CipherTensor(60, logQ, logs, (2,4,188, 1<<16))
    cts_b = scheme.encrypt_pairwise_upon(60, logQ, [random_floats[:]  for _ in range(4)])
    scheme.sub_pairwise_into(cts_a, cts_b)

    cts_a = CipherTensor(60, logQ, logs, (2,4,188, 1<<16))
    cts_a = scheme.encrypt_pairwise_upon(60, logQ, [random_floats[:]  for _ in range(4)])
    cts_b = CipherTensor(60, logQ, logs, (2,4,188, 1<<16))
    cts_b = scheme.encrypt_pairwise_upon(60, logQ, [random_floats[:]  for _ in range(4)])
    cuda.synchronize()
    start_time = time.perf_counter()
    scheme.sub_pairwise_into(cts_a, cts_b)
    cuda.synchronize()
    end_time = time.perf_counter()
    elapsed_time = end_time - start_time
    print(f"兩個密文相減的平均行時間: {elapsed_time:.4f} 秒")

    start_time = time.perf_counter()
    result = scheme.decrypt_pairwise_upon(cts_a)
    result = result[0]
    end_time = time.perf_counter()
    elapsed_time = end_time - start_time
    print(f"一個密文張量解密的平均行時間: {elapsed_time:.4f} 秒")
    print()
    print('+++++++++++++++++++++++++++ sub_pairwise_into +++++++++++++++++++++++++++')
    print()
    for i in range(4):
        error0 = math.fabs(random_floats[i].real - random_floats[i].real - result[i].real )
        error1 = math.fabs(random_floats[i].imag - random_floats[i].imag - result[i].imag )
        print(error0+error1, ', ', random_floats[i].real - random_floats[i].real, '  ==  ', result[i].real, ' : ', ', ', random_floats[i].imag - random_floats[i].imag, '  ==  ', result[i].imag)
    print()
    print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
    print()
    for i in range(4):
        print(random_floats[i] - random_floats[i], '  ---  ', result[i])

    print()
    print('+++++++++++++++++++++++++++ sub_pairwise_into +++++++++++++++++++++++++++')
    print()





    cts_a = CipherTensor(60, logQ, logs, (2,4,188, 1<<16))
    cts_a = scheme.encrypt_pairwise_upon(60, logQ, [random_floats[:]  for _ in range(4)])
    cts_b = CipherTensor(60, logQ, logs, (2,4,188, 1<<16))
    cts_b = scheme.encrypt_pairwise_upon(60, logQ, [random_floats[:]  for _ in range(4)])
    scheme.addconst_broadcast_into(cts_a, 1.23456789)

    cts_a = CipherTensor(60, logQ, logs, (2,4,188, 1<<16))
    cts_a = scheme.encrypt_pairwise_upon(60, logQ, [random_floats[:]  for _ in range(4)])
    cts_b = CipherTensor(60, logQ, logs, (2,4,188, 1<<16))
    cts_b = scheme.encrypt_pairwise_upon(60, logQ, [random_floats[:]  for _ in range(4)])
    cuda.synchronize()
    start_time = time.perf_counter()
    scheme.addconst_broadcast_into(cts_a, 1.23456789)
    cuda.synchronize()
    end_time = time.perf_counter()
    elapsed_time = end_time - start_time
    print(f"一個密文張量與常數broadcast相加的平均行時間: {elapsed_time:.4f} 秒")

    start_time = time.perf_counter()
    result = scheme.decrypt_pairwise_upon(cts_a)
    result = result[0]
    end_time = time.perf_counter()
    elapsed_time = end_time - start_time
    print(f"一個密文張量解密的平均行時間: {elapsed_time:.4f} 秒")
    print()
    print('+++++++++++++++++++++++++++ addconst_broadcast_into +++++++++++++++++++++++++++')
    print()
    for i in range(4):
        error0 = math.fabs(1.23456789+random_floats[i].real - result[i].real )
        error1 = math.fabs(random_floats[i].imag - result[i].imag )
        print(error0+error1, ', ', 1.23456789+random_floats[i].real, '  ==  ', result[i].real, ' : ', ', ', random_floats[i].imag, '  ==  ', result[i].imag)
    print()
    print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
    print()
    for i in range(4):
        print(1.23456789+random_floats[i], '  ---  ', result[i])

    print()
    print('+++++++++++++++++++++++++++ addconst_broadcast_into +++++++++++++++++++++++++++')
    print()








    consts = [ 1.23456789*i for i in range(1<<logs) ]
    cts_a = CipherTensor(60, logQ, logs, (2,4,188, 1<<16))
    cts_a = scheme.encrypt_pairwise_upon(60, logQ, [random_floats[:]  for _ in range(4)])
    cts_b = CipherTensor(60, logQ, logs, (2,4,188, 1<<16))
    cts_b = scheme.encrypt_pairwise_upon(60, logQ, [random_floats[:]  for _ in range(4)])
    scheme.addconst_pairwise_into(cts_a, consts)

    cts_a = CipherTensor(60, logQ, logs, (2,4,188, 1<<16))
    cts_a = scheme.encrypt_pairwise_upon(60, logQ, [random_floats[:]  for _ in range(4)])
    cts_b = CipherTensor(60, logQ, logs, (2,4,188, 1<<16))
    cts_b = scheme.encrypt_pairwise_upon(60, logQ, [random_floats[:]  for _ in range(4)])
    cuda.synchronize()
    start_time = time.perf_counter()
    scheme.addconst_pairwise_into(cts_a, consts)
    cuda.synchronize()
    end_time = time.perf_counter()
    elapsed_time = end_time - start_time
    print(f"一個密文張量與常數pairwise相加的平均行時間: {elapsed_time:.4f} 秒")

    start_time = time.perf_counter()
    result = scheme.decrypt_pairwise_upon(cts_a)
    result = result[3]
    end_time = time.perf_counter()
    elapsed_time = end_time - start_time
    print(f"一個密文張量解密的平均行時間: {elapsed_time:.4f} 秒")
    print()
    print('+++++++++++++++++++++++++++ addconst_pairwise_into +++++++++++++++++++++++++++')
    print()
    for i in range(4):
        error0 = math.fabs(1.23456789*3+random_floats[i].real - result[i].real )
        error1 = math.fabs(random_floats[i].imag - result[i].imag )
        print(error0+error1, ', ', 1.23456789*3+random_floats[i].real, '  ==  ', result[i].real, ' : ', ', ', random_floats[i].imag, '  ==  ', result[i].imag)
    print()
    print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
    print()
    for i in range(4):
        print(1.23456789*3+random_floats[i], '  ---  ', result[i])

    print()
    print('+++++++++++++++++++++++++++ addconst_pairwise_into +++++++++++++++++++++++++++')
    print()






    consts = [ 1.23456789*i for i in range(1<<logs) ]
    cts_a = CipherTensor(60, logQ, logs, (2,4,188, 1<<16))
    cts_a = scheme.encrypt_pairwise_upon(60, logQ, [random_floats[:]  for _ in range(4)])
    cts_b = CipherTensor(60, logQ, logs, (2,4,188, 1<<16))
    cts_b = scheme.encrypt_pairwise_upon(60, logQ, [random_floats[:]  for _ in range(4)])
    scheme.imult_pairwise_into(cts_a)

    cts_a = CipherTensor(60, logQ, logs, (2,4,188, 1<<16))
    cts_a = scheme.encrypt_pairwise_upon(60, logQ, [random_floats[:]  for _ in range(4)])
    cts_b = CipherTensor(60, logQ, logs, (2,4,188, 1<<16))
    cts_b = scheme.encrypt_pairwise_upon(60, logQ, [random_floats[:]  for _ in range(4)])
    cuda.synchronize()
    start_time = time.perf_counter()
    scheme.imult_pairwise_into(cts_a)
    cuda.synchronize()
    end_time = time.perf_counter()
    elapsed_time = end_time - start_time
    print(f"一個密文張量I乘法imult_pairwise的平均行時間: {elapsed_time:.4f} 秒")

    start_time = time.perf_counter()
    result = scheme.decrypt_pairwise_upon(cts_a)
    result = result[0]
    end_time = time.perf_counter()
    elapsed_time = end_time - start_time
    print(f"一個密文張量解密的平均行時間: {elapsed_time:.4f} 秒")
    print()
    print('+++++++++++++++++++++++++++ imult_pairwise_into +++++++++++++++++++++++++++')
    print()
    for i in range(4):
        error0 = math.fabs(random_floats[i].real - result[i].imag )
        error1 = math.fabs(-random_floats[i].imag - result[i].real )
        print(error0+error1, ', ', random_floats[i].real, '  ==  ', result[i].imag, ' : ', ', ', random_floats[i].imag, '  ==  ', -result[i].real)
    print()
    print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
    print()
    for i in range(4):
        print(random_floats[i], '  ---  ', result[i])

    print()
    print('+++++++++++++++++++++++++++ imult_pairwise_into +++++++++++++++++++++++++++')
    print()





    cts_a = CipherTensor(60, logQ, logs, (2,4,188, 1<<16))
    cts_a = scheme.encrypt_pairwise_upon(60, logQ, [random_floats[:]  for _ in range(4)])
    cts_b = CipherTensor(60, logQ, logs, (2,4,188, 1<<16))
    cts_b = scheme.encrypt_pairwise_upon(60, logQ, [random_floats[:]  for _ in range(4)])
    scheme.multconst_broadcast_into(cts_a, 1.23456789)

    cts_a = CipherTensor(60, logQ, logs, (2,4,188, 1<<16))
    cts_a = scheme.encrypt_pairwise_upon(60, logQ, [random_floats[:]  for _ in range(4)])
    cts_b = CipherTensor(60, logQ, logs, (2,4,188, 1<<16))
    cts_b = scheme.encrypt_pairwise_upon(60, logQ, [random_floats[:]  for _ in range(4)])
    cuda.synchronize()
    start_time = time.perf_counter()
    scheme.multconst_broadcast_into(cts_a, 1.23456789)
    cuda.synchronize()
    end_time = time.perf_counter()
    elapsed_time = end_time - start_time
    print(f"一個密文張量常數乘法multconst_broadcast的平均行時間: {elapsed_time:.4f} 秒")

    start_time = time.perf_counter()
    result = scheme.decrypt_pairwise_upon(cts_a)
    result = result[0]
    end_time = time.perf_counter()
    elapsed_time = end_time - start_time
    print(f"一個密文張量解密的平均行時間: {elapsed_time:.4f} 秒")
    print()
    print('+++++++++++++++++++++++++++ multconst_broadcast_into +++++++++++++++++++++++++++')
    print()
    for i in range(4):
        error0 = math.fabs(1.23456789*random_floats[i].real - result[i].real )
        error1 = math.fabs(1.23456789*random_floats[i].imag - result[i].imag )
        print(error0+error1, ', ', 1.23456789*random_floats[i].real, '  ==  ', result[i].real, ' : ', ', ', 1.23456789*random_floats[i].imag, '  ==  ', result[i].imag)
    print()
    print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
    print()
    for i in range(4):
        print(1.23456789*random_floats[i], '  ---  ', result[i])

    print()
    print('+++++++++++++++++++++++++++ multconst_broadcast_into +++++++++++++++++++++++++++')
    print()




    cnstvecs = [[0, 1, 2, 3], [0, 1, 2, 3], [0, 1, 2, 3], [0, 1, 2, 3]]
    cts_a = CipherTensor(60, logQ, logs, (2,4,188, 1<<16))
    cts_a = scheme.encrypt_pairwise_upon(60, logQ, [random_floats[:]  for _ in range(4)])
    cnstvecs = [[0, 1, 2, 3], [0, 1, 2, 3], [0, 1, 2, 3], [0, 1, 2, 3]]
    scheme.multconstvec_pairwise_into(cts_a, cnstvecs)

    cnstvecs = [[0, 1, 2, 3], [0, 1, 2, 3], [0, 1, 2, 3], [0, 1, 2, 3]]
    cts_a = CipherTensor(60, logQ, logs, (2,4,188, 1<<16))
    cts_a = scheme.encrypt_pairwise_upon(60, logQ, [random_floats[:]  for _ in range(4)])
    cnstvecs = [[0, 1, 2, 3], [0, 1, 2, 3], [0, 1, 2, 3], [0, 1, 2, 3]]
    cuda.synchronize()
    start_time = time.perf_counter()
    scheme.multconstvec_pairwise_into(cts_a, cnstvecs)
    cuda.synchronize()
    end_time = time.perf_counter()
    elapsed_time = end_time - start_time
    print(f"一個密文張量multconstvecs_pairwise的平均行時間: {elapsed_time:.4f} 秒")

    start_time = time.perf_counter()
    result = scheme.decrypt_pairwise_upon(cts_a)
    result = result[0]
    end_time = time.perf_counter()
    elapsed_time = end_time - start_time
    print(f"一個密文張量解密的平均行時間: {elapsed_time:.4f} 秒")
    print()
    print('+++++++++++++++++++++++++++ multconstvec_pairwise_into +++++++++++++++++++++++++++')
    print()
    for i in range(4):
        error0 = math.fabs(i*random_floats[i].real - result[i].real )
        error1 = math.fabs(i*random_floats[i].imag - result[i].imag )
        print(error0+error1, ', ', i*random_floats[i].real, '  ==  ', result[i].real, ' : ', ', ', i*random_floats[i].imag, '  ==  ', result[i].imag)
    print()
    print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
    print()
    for i in range(4):
        print(i*random_floats[i], '  ---  ', result[i])

    print()
    print('+++++++++++++++++++++++++++ multconstvec_pairwise_into +++++++++++++++++++++++++++')
    print()




    cts_a = CipherTensor(60, logQ, logs, (2,4,188, 1<<16))
    cts_a = scheme.encrypt_pairwise_upon(60, logQ, [random_floats[:]  for _ in range(4)])
    cts_b = CipherTensor(60, logQ, logs, (2,4,188, 1<<16))
    cts_b = scheme.encrypt_pairwise_upon(60, logQ, [random_floats[:]  for _ in range(4)])
    scheme.conjugate_pairwise_into(cts_a)

    cts_a = CipherTensor(60, logQ, logs, (2,4,188, 1<<16))
    cts_a = scheme.encrypt_pairwise_upon(60, logQ, [random_floats[:]  for _ in range(4)])
    cts_b = CipherTensor(60, logQ, logs, (2,4,188, 1<<16))
    cts_b = scheme.encrypt_pairwise_upon(60, logQ, [random_floats[:]  for _ in range(4)])
    cuda.synchronize()
    start_time = time.perf_counter()
    scheme.conjugate_pairwise_into(cts_a)
    cuda.synchronize()
    end_time = time.perf_counter()
    elapsed_time = end_time - start_time
    print(f"一個密文張量共軛算法conjugate_pairwise的平均行時間: {elapsed_time:.4f} 秒")

    start_time = time.perf_counter()
    result = scheme.decrypt_pairwise_upon(cts_a)
    result = result[0]
    end_time = time.perf_counter()
    elapsed_time = end_time - start_time
    print(f"一個密文張量解密的平均行時間: {elapsed_time:.4f} 秒")
    print()
    print('+++++++++++++++++++++++++++ conjugate_pairwise_into +++++++++++++++++++++++++++')
    print()
    for i in range(4):
        error0 = math.fabs(random_floats[i].real - result[i].real )
        error1 = math.fabs(random_floats[i].imag + result[i].imag )
        print(error0+error1, ', ', random_floats[i].real, '  ==  ', result[i].real, ' : ', ', ', -random_floats[i].imag, '  ==  ', result[i].imag)
    print()
    print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
    print()
    for i in range(4):
        print(random_floats[i], '  ---  ', result[i])

    print()
    print('+++++++++++++++++++++++++++ conjugate_pairwise_into +++++++++++++++++++++++++++')
    print()


    return 0





if __name__ == "__main__":
    main()